### PR TITLE
fix: Increase OPEN_TIMEOUT and move injects to own file

### LINKED ISSUE #351: :8888/xpra/:1624 Uncaught TypeError: Cannot read properties of undefined (reading 'id_to_window')
In the console.log the following message appears several times:

```
:8888/xpra/:1624 Uncaught TypeError: Cannot read properties of undefined (reading 'id_to_window')
    at :8888/xpra/:1624:66
(anonymous) @ :8888/xpra/:1624
setInterval
(anonymous) @ :8888/xpra/:1624
mightThrow @ jquery.js:3764
process @ jquery.js:3832
setTimeout
(anonymous) @ jquery.js:3870
fire @ jquery.js:3498
fireWith @ jquery.js:3628
fire @ jquery.js:3636
fire @ jquery.js:3498
fireWith @ jquery.js:3628
ready @ jquery.js:4108
completed @ jquery.js:4118
```

### PR DESCRIPTION
**Pull request by zusorio**
Closes #351
Somewhat improves #350

### CODE REVIEW

File: remote/client-inject.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
+/*
+ * SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+const injectInterval = setInterval(() => {
+    if (!client) return;
+    client.OPEN_TIMEOUT = 100_000;
```
Comment (MoritzWeber0) [inline remote/client-inject.js:8]:
```suggestion
    client.OPEN_TIMEOUT = 30_000;
```

100 seconds might be bit too long. If think it's sufficient to time out after 30 seconds.

**Review by MoritzWeber0 — APPROVED** [review]

**Comment by totaam** [comment]
Please see https://github.com/Xpra-org/xpra-html5/issues/336 for a much cleaner solution.
